<?php

return [
    'welcome' => 'Bienvenue !',
    'login' => 'Connexion',
    'email' => 'E-mail',
    'password' => 'Mot de Passe',
    'remember_me' => 'Se souvenir de moi',
    'login_button' => 'Connexion',
    'total_invoices' => 'Total des produits',
    'unpaid_invoices' => 'Produits impayés',
    'paid_invoices' => 'Produits payés',
    'partially_paid_invoices' => 'Produits partiellement payés',
    'statistics' => 'Statistiques',
    'Mad' => 'MAD',
    'Order_status' => 'Statut des produits',
    'Order_Status_and_Tracking' => "Statut et suivi des produits",
    'diag' => 'Diagramme circulaire des produits',

    #main-sidebar
    'invoicing_software' => 'Rubex Logiciel ',
    'Home' => 'Accueil',
    'invoices' => 'Produits',
    'Reports' => 'Rapports',
    'Users' => 'Utilisateurs',
    'Settings' => 'Paramètres',
    'List_of_users' => 'Liste des utilisateurs',
    'List_of_invoices' => 'Liste des produits',
    'Invoice_archive' => 'Archives des produits',
    'Billing_reports' => 'Rapports de facturation',
    'product' => 'Recettes',
    'expenses' => 'Dépenses',

    #invoice-page
    'invoice_number' => 'Numéro du produit',
    'invoice_date' => 'Date du produit',
    'due_date' => "Date d'échéance",
    'recette' => 'Recette',
    'price' => 'Prix',
    'state' => 'État',
    'operations' => 'Opérations',
    'notes' => 'Remarques',
    'update' => 'Mettre à jour',
    'Update_invoice_status' => 'Mettre à jour le statut du produit',
    'move_to_archive' => "Déplacer vers l'archive",
    'delete' => 'Supprimer',
    'print_the_invoice' => 'Imprimer le produit',
    'delete_invoice' => 'Voulez-vous supprimer ce produit ?',
    'Update_invoice_statuse' => 'Mettre à jour le statut du produit',
    'Choose_the_status' => 'Choisissez le statut',
    'Paid' => 'Payé',
    'unpaid' => 'Non payé',
    'processing_paid' => 'Partiellement payé',
    'save' => 'Sauvegarder',
    'List_of_invoices' => 'Liste des produits',
    'Add_an_invoice' => 'Ajouter un produit',
    'okay_transfer' => 'Voulez-vous transférer le produit dans les archives ?',
    'Invoice_archive' => 'Archives des produits',
    'Print_an_invoice' => 'Imprimer un produit',

    #create_invoice
    'Add_an_invoice' => 'Ajouter un produit',
    'Please_enter' => 'Veuillez saisir le numéro de produit',
    'Select_the_section' => 'Sélectionnez la dépense',
    'Attachment_format' => 'Format de pièce jointe',
    'Attachments' => 'Pièces jointes',
    'okay_transfer_from' => 'Voulez-vous transférer le produit des archives ?',
    'Move_from_archive' => 'Déplacer des archives',
    'Update_invoice' => 'Mettre à jour le produit',
    'The_attachment_added successfully' => 'La pièce jointe a été ajoutée avec succès',
    'The_expense' => 'La dépense a été ajoutée avec succès',
    'The_expense_deleted' => 'La dépense a été supprimée avec succès',
    'section_updated_successfully' => 'La dépense a été modifiée avec succès',
    'add_expense' => 'Ajouter une dépense',
    'expense_name' => 'Nom de la dépense',
    'description' => 'Description',
    'Add' => 'Ajouter',
    'Added_by' => 'Ajouté par',
    'delete_this_expense' => 'Voulez-vous supprimer cette dépense ?',
    'update_expense' => 'Modifier une dépense',

    #recipe
    'Add_a_product' => 'Ajouter une recette',
    'delete_this_recipe?' => 'Voulez-vous supprimer cette recette ?',
    'Recipe_name' => 'Nom de la recette',
    'List_of_recipes' => 'Liste des recettes',
    'product_added_successfully' => 'La recette a été ajoutée avec succès',
    'product_updated_successfully' => 'La recette a été mise à jour avec succès',
    'product_deleted_successfully' => 'La recette a été supprimée avec succès',

    'invoice_status_updated_successfully' => 'Statut du produit mis à jour avec succès',
    'Invoice_added_successfully' => 'Produit ajouté avec succès',
    'Invoice_moved_successfully' => 'Produit déplacé avec succès',
    'invoice_updated_successfully' => 'Produit mis à jour avec succès',
    'invoice_deleted_successfully' => 'Produit supprimé avec succès',
    'Invoice_details' => 'Détails du produit',
    'Billing_information' => 'Informations de facturation',
    'file_name' => 'Nom de fichier',
    'Date_added' => "Date d'ajout",
    'Add_attachment' => 'Ajouter une pièce jointe',
    'Show' => 'Afficher',
    'download' => 'Télécharger',
    'delete_attachment' => 'Voulez-vous supprimer cette pièce jointe ?',
    'Attachment_format' => 'Format de pièce jointe',
    'Attachment_added_successfully' => 'La pièce jointe a été ajoutée avec succès',
    'Attachment_deleted_successfully' => 'La pièce jointe a été supprimée avec succès',

    'Search_by_invoice_number' => 'Recherche par numéro de produit',
    'Billing_report' => 'Rapport de facturation',
    'Search' => 'Recherche',
    'invoice' => 'Produit',
    'No_notes' => 'Aucune note',

    #users
    'user_name' => "Nom d'utilisateur",
    'Add_user' => 'Ajouter un utilisateur',
    'Back' => 'Retour',
    'confirm_password' => 'Confirmez le mot de passe',
    'Enabled' => 'Activé',
    'Not_enabled' => 'Non activé',
    'Confirm' => 'Valider',
    'User_modification' => "Modification de l'utilisateur",
    'user_created_successfully' => 'Utilisateur créé avec succès',
    'user_updated_successfully' => "L'utilisateur a été mis à jour avec succès",
    'user_deleted_successfully' => 'Utilisateur supprimé avec succès',

    #print the invoice
    'Print_the_invoice' => 'Imprimer le produit',
    'Print' => 'Imprimer',
    'Notifications' => 'Notifications',
    'Must_read_all' => 'Il faut tout lire',
    'Number_of_unread_notifications:' => 'Nombre de notifications non lues :',
    'VIEW_ALL:' => 'VOIR TOUT',
    'Log_out' => 'Déconnexion',

    'Recherche_par_dates' => 'Recherche par dates',
    'Search_by_invoice_number' => 'Recherche par numéro de produit',
    'from_date' => 'De la date',
    'Until_date' => "Jusqu'à la date",
    'Export_to_CSV' => 'Exporter en CSV',
];

?>
