<?php

return [
    'welcome' => 'Welcome!',
    'login' => 'Login',
    'email' => 'Email',
    'password' => 'Password',
    'remember_me' => 'Remember me',
    'login_button' => 'Login',
    'total_invoices' => 'Total products',
    'unpaid_invoices' => 'Unpaid products',
    'paid_invoices' => 'Paid products',
    'partially_paid_invoices' => 'Processing paid products',
    'statistics' => 'Statistics',
    'Mad' => 'MAD',
    'Order_status' => 'Products status',
    'Order_Status_and_Tracking' => 'Products Status and Tracking',
    'diag' => 'Product pie chart',

    #main-sidebar
    'invoicing_software' => 'Rubex software',
    'Home' => 'Home',
    'invoices' => 'Products',
    'Reports' => 'Reports',
    'Users' => 'Users',
    'Settings' => 'Settings',
    'List_of_users' => 'List of users',
    'List_of_invoices' => 'List of products',
    'Invoice_archive' => 'Product archive',
    'Billing_reports' => 'Billing reports',
    'product' => 'Recipes',
    'expenses' => 'Expenses',

    #invoice-page
    'invoice_number' => 'Product number',
    'invoice_date' => 'Product date',
    'due_date' => 'Due date',
    'recette' => 'Recipe',
    'price' => 'Price',
    'state' => 'State',
    'operations' => 'Operations',
    'notes' => 'Notes',
    'update' => 'Update',
    'Update_invoice_status' => 'Update product status',
    'move_to_archive' => 'Move to archive',
    'delete' => 'Delete',
    'print_the_invoice' => 'Print the product',
    'delete_invoice' => 'Do you want to delete this product?',
    'Update_invoice_statuse' => 'Update product status',
    'Choose_the_status' => 'Choose the status',
    'Paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'processing_paid' => 'Processing paid',
    'save' => 'Save',
    'List_of_invoices' => 'List of products',
    'Add_an_invoice' => 'Add a product',
    'okay_transfer' => 'Do you want to transfer the product to the archive?',
    'Invoice_archive' => 'Product archive',
    'Print_an_invoice' => 'Print a product',

    #create_invoice
    'Add_an_invoice' => 'Add a product',
    'Please_enter' => 'Please enter the product number',
    'Select_the_section' => 'Select the Expense',
    'Attachment_format' => 'Attachment format',
    'Attachments' => 'Attachments',
    'okay_transfer_from' => 'Do you want to transfer the product from the archive?',
    'Move_from_archive' => 'Move from archive',
    'Update_invoice' => 'Update product',
    'The_attachment_added_successfully' => 'The attachment was added successfully',
    'The_expense' => 'The expense has been added successfully',
    'The_expense_deleted' => 'The expense has been deleted successfully',
    'section_updated_successfully' => 'The expense has been updated successfully',
    'add_expense' => 'Add an expense',
    'expense_name' => 'Expense name',
    'description' => 'Description',
    'Add' => 'Add',
    'Added_by' => 'Added by',
    'delete_this_expense' => 'Do you want to delete this expense?',
    'update_expense' => 'Expense update',

    #recipe
    'Add_a_product' => 'Add a recipe',
    'delete_this_recipe?' => 'Do you want to delete this recipe?',
    'Recipe_name' => 'Recipe name',
    'List_of_recipes' => 'List of recipes',
    'product_added_successfully' => 'The recipe has been added successfully',
    'product_updated_successfully' => 'The recipe has been updated successfully',
    'product_deleted_successfully' => 'The recipe has been deleted successfully',

    'invoice_status_updated_successfully' => 'Product status updated successfully',
    'Invoice_added_successfully' => 'Product added successfully',
    'Invoice_moved_successfully' => 'Product moved successfully',
    'invoice_updated_successfully' => 'Product updated successfully',
    'invoice_deleted_successfully' => 'Product deleted successfully',
    'Invoice_details' => 'Product details',
    'Billing_information' => 'Billing information',
    'file_name' => 'File name',
    'Date_added' => 'Date added',
    'Add_attachment' => 'Add attachment',
    'Show' => 'Show',
    'download' => 'Download',
    'delete_attachment' => 'Do you want to delete this attachment?',
    'Attachment_format' => 'Attachment format',
    'Attachment_added_successfully' => 'Attachment added successfully',
    'Attachment_deleted_successfully' => 'Attachment deleted successfully',

    'Search_by_invoice_number' => 'Search by product number',
    'Billing_report' => 'Billing report',
    'Search' => 'Search',
    'invoice' => 'Product',
    'No_notes' => 'No notes',

    #users
    'user_name' => 'User name',
    'Add_user' => 'Add user',
    'Back' => 'Back',
    'confirm_password' => 'Confirm password',
    'Enabled' => 'Enabled',
    'Not_enabled' => 'Not enabled',
    'Confirm' => 'Confirm',
    'User_modification' => 'User modification',
    'user_created_successfully' => 'User created successfully',
    'user_updated_successfully' => 'User updated successfully',
    'user_deleted_successfully' => 'User deleted successfully',

    #print the invoice
    'Print_the_invoice' => 'Print the product',
    'Print' => 'Print',
    'Notifications' => 'Notifications',
    'Must_read_all' => 'Must read all',
    'Number_of_unread_notifications:' => 'Number of unread notifications:',
    'VIEW_ALL:' => 'VIEW ALL',
    'Log_out' => 'Log out',

    'Recherche_par_dates' => 'Search by dates',
    'Search_by_invoice_number' => 'Search by product number',
    'from_date' => 'From the date',
    'Until_date' => 'Until date',
    'Export_to_CSV' => 'Export to CSV',
];

?>
