<?php

return [
    'welcome' => 'مرحبا بك',
    'login' => 'تسجيل الدخول',
    'email' => 'البريد الالكتروني',
    'password' => 'كلمة المرور',
    'remember_me' => 'تذكرني',
    'login_button' => 'تسجيل الدخول',
    'total_invoices' => 'إجمالي المنتجات',
    'unpaid_invoices' => 'المنتجات الغير مدفوعة',
    'paid_invoices' => 'المنتجات المدفوعة',
    'partially_paid_invoices' => 'المنتجات المدفوعة جزئياً',
    'statistics' => 'الإحصائيات',
    'Mad' => 'درهم',
    'Order_status' => 'حالة المنتجات',
    'Order_Status_and_Tracking' => 'حالة وتتبع المنتجات',
    'diag' => 'الرسم البياني للمنتجات',

    #main-sidebar
    'invoicing_software' => 'برنامج المنتجات',
    'Home' => 'الرئيسية',
    'invoices' => 'المنتجات',
    'Reports' => 'التقارير',
    'Users' => 'المستخدمين',
    'Settings' => 'الإعدادات',
    'List_of_users' => 'قائمة المستخدمين',
    'List_of_invoices' => 'قائمة المنتجات',
    'Invoice_archive' => 'أرشيف المنتجات',
    'Billing_reports' => 'تقارير المنتجات',
    'product' => 'وصفات',
    'expenses' => 'نفقات',

    #invoice-page
    'invoice_number' => 'رقم المنتج',
    'invoice_date' => 'تاريخ المنتج',
    'due_date' => 'تاريخ الاستحقاق',
    'recette' => 'وصفة',
    'price' => 'المبلغ',
    'state' => 'الحالة',
    'operations' => 'العمليات',
    'notes' => 'الملاحظات',
    'update' => 'تحديث',
    'Update_invoice_status' => 'تحديث حالة المنتج',
    'move_to_archive' => 'نقل إلى الأرشيف',
    'delete' => 'حذف',
    'print_the_invoice' => 'طباعة المنتج',
    'delete_invoice' => 'هل تريد حذف هذا المنتج؟',
    'Update_invoice_statuse' => 'تحديث حالة المنتج',
    'Choose_the_status' => 'اختر الحالة',
    'Paid' => 'مدفوع',
    'unpaid' => 'غير مدفوع',
    'processing_paid' => 'مدفوع جزئياً',
    'save' => 'حفظ البيانات',
    'List_of_invoices' => 'قائمة المنتجات',
    'Add_an_invoice' => 'أضف منتجاً',
    'okay_transfer' => 'هل تريد نقل المنتج إلى الأرشيف؟',
    'Invoice_archive' => 'أرشيف المنتجات',
    'Print_an_invoice' => 'طباعة منتج',

    #create_invoice
    'Add_an_invoice' => 'إضافة منتج',
    'Please_enter' => 'يرجى إدخال رقم المنتج',
    'Select_the_section' => 'حدد القسم',
    'Attachment_format' => 'صيغة المرفق',
    'Attachments' => 'المرفقات',
    'okay_transfer_from' => 'هل تريد نقل المنتج من الأرشيف؟',
    'Move_from_archive' => 'نقل من الأرشيف',
    'Update_invoice' => 'تحديث المنتج',
    'The_attachment_added successfully' => 'تمت إضافة المرفق بنجاح',
    'The_expense' => 'تمت إضافة النفقة بنجاح',
    'The_expense_deleted' => 'تم حذف النفقة بنجاح',
    'section_updated_successfully' => 'تم تعديل النفقة بنجاح',
    'add_expense' => 'إضافة نفقة',
    'expense_name' => 'اسم النفقة',
    'description' => 'وصف',
    'Add' => 'أضف',
    'Added_by' => 'أضيف من طرف',
    'delete_this_expense' => 'هل تريد حذف هذه النفقة؟',
    'update_expense' => 'تحديث النفقة',

    #recipe
    'Add_a_product' => 'أضف وصفة',
    'delete_this_recipe?' => 'هل تريد حذف هذه الوصفة؟',
    'Recipe_name' => 'اسم الوصفة',
    'List_of_recipes' => 'قائمة الوصفات',
    'product_added_successfully' => 'تمت إضافة الوصفة بنجاح',
    'product_updated_successfully' => 'تم تحديث الوصفة بنجاح',
    'product_deleted_successfully' => 'تم حذف الوصفة بنجاح',

    'invoice_status_updated_successfully' => 'تم تحديث حالة المنتج بنجاح',
    'Invoice_added_successfully' => 'تمت إضافة المنتج بنجاح',
    'Invoice_moved_successfully' => 'تم نقل المنتج بنجاح',
    'invoice_updated_successfully' => 'تم تعديل المنتج بنجاح',
    'invoice_deleted_successfully' => 'تم حذف المنتج بنجاح',
    'Invoice_details' => 'تفاصيل المنتج',
    'Billing_information' => 'معلومات المنتج',
    'file_name' => 'اسم الملف',
    'Date_added' => 'تاريخ الإضافة',
    'Add_attachment' => 'أضف مرفق',
    'Show' => 'عرض',
    'download' => 'تحميل',
    'delete_attachment' => 'هل تريد حذف هذا المرفق؟',
    'Attachment_format' => 'صيغة المرفق',
    'Attachment_added_successfully' => 'تمت إضافة المرفق بنجاح',
    'Attachment_deleted_successfully' => 'تم حذف المرفق بنجاح',

    'Search_by_invoice_number' => 'بحث برقم المنتج',
    'Billing_report' => 'تقرير المنتجات',
    'Search' => 'بحث',
    'invoice' => 'المنتج',
    'No_notes' => 'لا ملاحظات',

    #users
    'user_name' => 'اسم المستخدم',
    'Add_user' => 'إضافة مستخدم',
    'Back' => 'رجوع',
    'confirm_password' => 'تأكيد كلمة المرور',
    'Enabled' => 'مفعل',
    'Not_enabled' => 'غير مفعل',
    'Confirm' => 'تأكيد',
    'User_modification' => 'تعديل المستخدم',
    'user_created_successfully' => 'تم إنشاء المستخدم بنجاح',
    'user_updated_successfully' => 'تم تحديث المستخدم بنجاح',
    'user_deleted_successfully' => 'تم حذف المستخدم بنجاح',

    #print the invoice
    'Print_the_invoice' => 'طباعة المنتج',
    'Print' => 'طباعة',
    'Notifications' => 'الإشعارات',
    'Must_read_all' => 'يجب قراءة الكل',
    'Number_of_unread_notifications:' => 'عدد الإشعارات غير المقروءة:',
    'VIEW_ALL:' => 'عرض الكل',
    'Log_out' => 'تسجيل الخروج',

    'Recherche_par_dates' => 'بحث حسب التواريخ',
    'Search_by_invoice_number' => 'بحث برقم المنتج',
    'from_date' => 'من التاريخ',
    'Until_date' => 'حتى تاريخ',
    'Export_to_CSV' => 'تصدير إلى CSV',
];

?>
